import Link from "next/link"

const pillars = [
  ["01", "Read", "Build a steady knowledge of Islam with clear, Islamic lessons."],
  ["02", "Learn", "Strengthen understanding of Islam in Tamil through Challenging Quizzes."],
  ["03", "Grow", "Keep learning together with family and community."],
]

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <header className="border-b border-border/70"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5 lg:px-8"><Link href="/" className="flex items-center gap-3" aria-label="IQRA Tamil home"><span className="flex size-10 items-center justify-center rounded-full bg-primary font-serif text-xl text-primary-foreground">ق</span><span className="font-semibold tracking-tight">IQRA <span className="text-primary">TAMIL</span></span></Link><span className="hidden text-sm text-muted-foreground sm:block">Learn with purpose. Grow with community.</span></div></header>
      <section className="mx-auto grid max-w-6xl gap-12 px-6 pb-20 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-28"><div><p className="mb-6 font-mono text-xs font-semibold uppercase tracking-[0.24em] text-primary">A new chapter is beginning</p><h1 className="max-w-3xl text-balance font-serif text-5xl leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">Learn, reflect, and grow in <span className="text-primary">Tamil.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">IQRA Tamil is a simple, welcoming place for Tamil-speaking families to build Quranic reading and Islamic learning into everyday life.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#next" className="inline-flex items-center justify-center rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5">See what&apos;s next <span className="ml-2" aria-hidden="true">→</span></a><a href="#why" className="inline-flex items-center justify-center rounded-full border border-border px-6 py-3.5 text-sm font-semibold transition-colors hover:bg-muted">Why IQRA Tamil</a></div></div><div className="relative flex min-h-[360px] items-center justify-center rounded-[2rem] border border-border bg-card p-8 shadow-sm"><div className="absolute left-8 top-8 font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Read / Learn / Grow</div><div className="text-center"><p className="font-serif text-8xl text-primary/90" lang="ar" dir="rtl">اقرأ</p><p className="mt-4 font-serif text-2xl">Begin with “Read”</p><p className="mt-2 text-sm text-muted-foreground">A thoughtful learning experience is on its way.</p></div><div className="absolute bottom-8 right-8 size-3 rounded-full bg-accent" /></div></section>
      <section id="why" className="border-y border-border bg-muted/45"><div className="mx-auto max-w-6xl px-6 py-16 lg:px-8 lg:py-20"><div className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><h2 className="max-w-md text-3xl font-serif tracking-tight sm:text-4xl">A foundation for lifelong learning.</h2><p className="max-w-sm text-sm leading-6 text-muted-foreground">Made for Tamil-speaking learners, families, and communities who want learning to feel close to home.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-border bg-border md:grid-cols-3">{pillars.map(([number, title, copy]) => <article key={number} className="bg-background p-7"><p className="font-mono text-xs text-primary">{number}</p><h3 className="mt-12 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section>
      <section id="next" className="mx-auto max-w-6xl px-6 py-20 lg:px-8 lg:py-28"><div className="flex flex-col gap-8 rounded-[2rem] bg-primary px-7 py-10 text-primary-foreground sm:px-12 sm:py-14 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary-foreground/70">Coming next</p><h2 className="mt-4 max-w-xl text-4xl font-serif tracking-tight sm:text-5xl">The Quran Challenge</h2><p className="mt-4 max-w-lg leading-7 text-primary-foreground/80">A focused way to practice, reflect, and keep your progress moving. We&apos;re preparing it with care.</p></div><Link href="/challenge/quran-001" className="w-fit rounded-full border border-primary-foreground/30 px-5 py-2.5 text-sm font-semibold transition-colors hover:bg-primary-foreground/10">Start challenge <span className="ml-2" aria-hidden="true">→</span></Link></div></section>
      <footer className="border-t border-border"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-6 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>© 2026 IQRA Tamil</span><span>Built for the next generation of learners.</span></div></footer>
    </main>
  )
}
